DATA:
  NUM_FRAMES: 8
  SAMPLING_RATE: 1
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3, 3]
  FRAME_SAMPLING: 'like omnivore'
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.485, 0.456, 0.406]
MODEL:
  MODEL_NAME: 'TSM'
  MODALITY: 'RGB' # RGB, Flow, Both
  BASE_MODEL: 'resnet50'
  NUM_CLASSES: [97,300]
  NUM_SEGMENTS: 8
  SEGMENT_LENGTH: [1,5] # RGB:1, Flow: 5
  BEFORE_SOFTMAX: True
  DROPOUT_RATE: 0.7
  CROP_NUM: 1
  CONCENSUS_TYPE: 'avg'
  PARTIAL_BN: True
  IS_SHIFT: True
  SHIFT_DIV: 8
  SHIFT_PLACE: 'blockres'
  FC_LR5: False
  TEMPORAL_POOL: False
  NON_LOCAL: False
TEST:
  CHECKPOINT_FILE_PATH: 'checkpoint/tsm'
  ENABLE: True
  DATASET: epickitchens
  BATCH_SIZE: 4
  NUM_SPATIAL_CROPS: 1
  NUM_ENSEMBLE_VIEWS: 1
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
EPICKITCHENS:
  TRAIN_PLUS_VAL: False
NUM_GPUS: 1
OUTPUT_DIR: output
